name: CI Build Pipeline

#This tells GitHub WHEN to run the pipeline
on:
   push:
     branches:
      - main
   pull_request:
     branches:
       - main


#This tells GitHub WHAT to do
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      #Step 1: Download the code onto the temporary GitHub server
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in t Docker Hub
       # This securely pipes your password into the docker login command
        run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}"

        #Step 2: Build the Docker image to make sure the code compiles correctly
      - name: Build and Push Docker image
        run: |
          # We tag the image with your Docker username so Docker Hub knows it belongs to me
          docker build -t ${{ secrets.DOCKER_USERNAME }}/affordable-braids-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME}}/affordable-braids-app:latest
